remote_theme: yaoyao-liu/minimal-light
title: Guniet Dhillon
position: Computer Science Student
affiliation: University of Washington
email: gunietdhillon@gmail.com
github_link: https://github.com/Guniet123
linkedin: https://www.linkedin.com/in/guniet-dhillon-7a8664307
avatar: ./assets/profile.png

auto_dark_mode: true
